In [ ]:
import pandas as pd 
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
data = pd.read_csv('/content/drive/My Drive/Python/apriori.csv') 
data.head()

   susu  roti  biskuit  mentega  gula  kopi
0     1     1        1        1     0     0
1     1     0        1        0     1     1
2     1     0        0        0     1     1
3     1     0        1        0     1     1
4     0     1        0        1     0     1

In [ ]:
# Building the model 
frq_items = apriori(data, min_support = 0.4, use_colnames = True)

# Collecting the inferred rules in a dataframe
rules = association_rules(frq_items, min_threshold=0) 
rules = rules.sort_values(['confidence'], ascending =[False]) 
display(rules[['antecedents', 'consequents', 'support', 'confidence']])

              antecedents            consequents  support  confidence
26           (susu, kopi)                 (gula)      0.6    1.000000
38  (susu, biskuit, kopi)                 (gula)      0.4    1.000000
27           (susu, gula)                 (kopi)      0.6    1.000000
28           (kopi, gula)                 (susu)      0.6    1.000000
16        (biskuit, gula)                 (susu)      0.4    1.000000
13                 (gula)                 (kopi)      0.6    1.000000
31                 (gula)           (susu, kopi)      0.6    1.000000
32        (biskuit, kopi)                 (gula)      0.4    1.000000
22        (biskuit, kopi)                 (susu)      0.4    1.000000
33        (biskuit, gula)                 (kopi)      0.4    1.000000
39  (susu, biskuit, gula)                 (kopi)      0.4    1.000000
7               (mentega)                 (roti)      0.4    1.000000
6                  (roti)              (mentega)      0.4    1.000000
41  (biskuit, kopi, gula)                 (susu)      0.4    1.000000
45        (biskuit, kopi)           (susu, gula)      0.4    1.000000
3                  (gula)                 (susu)      0.6    1.000000
46        (biskuit, gula)           (susu, kopi)      0.4    1.000000
1               (biskuit)                 (susu)      0.6    1.000000
30                 (kopi)           (susu, gula)      0.6    0.750000
29                 (susu)           (kopi, gula)      0.6    0.750000
0                  (susu)              (biskuit)      0.6    0.750000
2                  (susu)                 (gula)      0.6    0.750000
4                  (susu)                 (kopi)      0.6    0.750000
5                  (kopi)                 (susu)      0.6    0.750000
12                 (kopi)                 (gula)      0.6    0.750000
21           (susu, kopi)              (biskuit)      0.4    0.666667
20        (susu, biskuit)                 (kopi)      0.4    0.666667
49              (biskuit)     (susu, kopi, gula)      0.4    0.666667
47           (kopi, gula)        (susu, biskuit)      0.4    0.666667
44           (susu, gula)        (biskuit, kopi)      0.4    0.666667
43           (susu, kopi)        (biskuit, gula)      0.4    0.666667
42        (susu, biskuit)           (kopi, gula)      0.4    0.666667
40     (susu, kopi, gula)              (biskuit)      0.4    0.666667
8               (biskuit)                 (gula)      0.4    0.666667
9                  (gula)              (biskuit)      0.4    0.666667
37                 (gula)        (biskuit, kopi)      0.4    0.666667
51                 (gula)  (susu, biskuit, kopi)      0.4    0.666667
35              (biskuit)           (kopi, gula)      0.4    0.666667
34           (kopi, gula)              (biskuit)      0.4    0.666667
10              (biskuit)                 (kopi)      0.4    0.666667
14        (susu, biskuit)                 (gula)      0.4    0.666667
15           (susu, gula)              (biskuit)      0.4    0.666667
18              (biskuit)           (susu, gula)      0.4    0.666667
19                 (gula)        (susu, biskuit)      0.4    0.666667
24              (biskuit)           (susu, kopi)      0.4    0.666667
11                 (kopi)              (biskuit)      0.4    0.500000
17                 (susu)        (biskuit, gula)      0.4    0.500000
25                 (kopi)        (susu, biskuit)      0.4    0.500000
48                 (susu)  (biskuit, kopi, gula)      0.4    0.500000
23                 (susu)        (biskuit, kopi)      0.4    0.500000
50                 (kopi)  (susu, biskuit, gula)      0.4    0.500000
36                 (kopi)        (biskuit, gula)      0.4    0.500000

In [ ]:
cols = ['antecedents','consequents']
rules[cols] = rules[cols].applymap(lambda x: tuple(x))

In [ ]:
rules.to_excel('/content/drive/My Drive/Python/apriori_res40.xlsx', index=False, columns=['antecedents', 'consequents', 'support', 'confidence'])